/*
 * This source file was generated by the Gradle 'init' task
 */
package org.uxworkshop;

public class App {
    public String getGreeting() {
        return "Hello World";
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
        app.oneOrOther(true);
    }

    public void oneOrOther(boolean choice) {
        if(choice) {
            System.out.println("Choice!");
        } else {
            System.out.println("Not Choice!");
        }
    }

}
